version: '3'

networks:
 zabbix_network:
    driver: bridge

services:
 zabbix-web:
   hostname: zabbix-web
   build: ./zabbix-web
   links:
     - postgresql-11:pg
   depends_on:
     - postgresql-11
     - zabbix-server
     - zabbix-agent
   networks:
     - zabbix_network

 zabbix-server:
   hostname: zabbix-server
   build: ./zabbix-server
   links:
     - postgresql-11:pg
   depends_on:
     - postgresql-11
   ports:
     - "10051:10051"
   networks:
     - zabbix_network

 zabbix-agent:
   hostname: zabbix-agent
   build: ./zabbix-agent
   ports:
    - "10050:10050"
   networks:
    - zabbix_network

 postgresql-11:
   hostname: postgresql
   build: ./postgresql-11
   ports:
    - "15432:5432"
   environment:
    POSTGRES_PASSWORD: password
   networks:
    - zabbix_network

 phppgadmin:
   hostname: phppgadmin
   build: ./phpPgAdmin
   links:
    - postgresql-11:pg
   depends_on:
    - postgresql-11
   ports:
    - "29000:80"
   environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: password
   networks:
    - zabbix_network
